### ISSUE TITLE
Support GOOD/BAD values in TagItem when reading from a subscription

### ISSUE THREAD

**Issue by sevren** [FlexLink/cgoopc#1]
Currently there seems to be no way to obtain the UA_Status code from the underlying c library when using the ua_driver. 

 Please enhance the `TagItem` Struct defined in https://github.com/FlexLink/cgoopc/blob/master/ua_wrapper.go#L91-L101
With an extra member. 
```
Quality int
```
When the subscription reads a new TagItem I would like the following functionality:
1. check that the underlying UA_Status is "good" (UA_STATUSCODE_GOOD )  set the 
`cgoopc.TagItem.Quality := 0 `
2. If the UA_Status is anything else set `cgoopc.TagItem.Quality := 1`

**Comment by snubydev** [comment]
fixed, so I'm closing this
